<?php

class Picqer_PostNL_Model_Sales_Order_Api extends Mage_Sales_Model_Order_Api
{

    /**
     * API call returns PostNL shipping info generated by TIG_PostNL
     *
     * @param $orderIncrementId
     *
     * @return array
     */
    public function picqerPostNL($orderIncrementId)
    {
        $active = Mage::getStoreConfig('picqer_shipping_options/postnl_settings/picqer_postnl_active');
        if ($active != 1)
        {
            return [ ];
        }

        $order = $this->_initOrder($orderIncrementId);

        // Check if TIG_PostNL is installed and enabled
        $tigInstalled = Mage::helper('core')->isModuleEnabled('TIG_PostNL');
        if ( ! $tigInstalled) {
            return [ ];
        }

        // Fetch TIG_PostNL order
        $tigPostNlOrder = Mage::getModel('postnl_core/order')->loadByOrder($order);

        // Get the store time zone and change times to match the correct time zone
        $storeTimezone = Mage::getStoreConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE,
            $tigPostNlOrder->getStoreId());
        $storeTimezone = new DateTimeZone($storeTimezone);

        if ($tigPostNlOrder->hasExpectedDeliveryTimeEnd()) {
            $expectedDeliveryTimeEnd = $this->toCorrectTimeZone($tigPostNlOrder->getExpectedDeliveryTimeEnd(),
                $storeTimezone)->format('H:i');
        } else {
            $expectedDeliveryTimeEnd = null;
        }

        // Add TIG_PostNL information to API
        $result = [
            'confirmDate'               => $this->toCorrectTimeZone($tigPostNlOrder->getConfirmDate(), $storeTimezone)
                ->format('Y-m-d H:i:s'),
            'isActive'                  => $tigPostNlOrder->getIsActive(),
            'shipmentCosts'             => $tigPostNlOrder->getShipmentCosts(),
            'productCode'               => $tigPostNlOrder->getProductCode(),
            'isPakjeGemak'              => $tigPostNlOrder->getIsPakjeGemak(),
            'isCanceled'                => $tigPostNlOrder->getIsCanceled(),
            'deliveryDate'              => $this->toCorrectTimeZone($tigPostNlOrder->getDeliveryDate(), $storeTimezone)
                ->format('Y-m-d H:i:s'),
            'type'                      => $tigPostNlOrder->getType(),
            'mobilePhoneNumber'         => $tigPostNlOrder->getMobilePhoneNumber(),
            'isPakketautomaat'          => $tigPostNlOrder->getIsPakketautomaat(),
            'options'                   => $tigPostNlOrder->getUnserializedOptions(),
            'expectedDeliveryTimeStart' => $this->toCorrectTimeZone($tigPostNlOrder->getExpectedDeliveryTimeStart(),
                $storeTimezone)->format('H:i'),
            'expectedDeliveryTimeEnd'   => $expectedDeliveryTimeEnd,
            'pakjeGemakAddress'         => $tigPostNlOrder->getIsPakjeGemak() || $tigPostNlOrder->getIsPakketautomaat() ? $this->_getAttributes($tigPostNlOrder->getPakjeGemakAddress(),
                'order_address') : null,
        ];

        return $result;
    }


    /**
     * Change the time zone of a date and time
     *
     * @param              $value
     * @param DateTimeZone $dateTimeZone
     *
     * @return DateTime
     */
    private function toCorrectTimeZone($value, DateTimeZone $dateTimeZone)
    {
        $dateTime = new DateTime($value);
        $dateTime->setTimezone($dateTimeZone);

        return $dateTime;
    }

}